apiVersion: v1
kind: Namespace
metadata:
  name: cafeteria
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: cafeteria
type: Opaque
data:
  username: cG9zdGdyZXM=  # postgres
  password: cG9zdGdyZXM=  # postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: cafeteria
type: Opaque
data:
  secret: ZGV2c3ByaW50LTIwMjYtc2VjcmV0LWtleQ==  # devsprint-2026-secret-key
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: cafeteria
data:
  DB_USER: "postgres"
  DB_PORT: "5432"
  REDIS_URL: "redis://redis:6379"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
  STOCK_SERVICE_URL: "http://stock-service:4002"
  NOTIFICATION_HUB_URL: "http://notification-hub:4005"
  GATEWAY_URL: "http://order-gateway:8080"
