apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: cafeteria
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "identity-provider"
        static_configs:
          - targets: ["identity-provider:4001"]

      - job_name: "order-gateway"
        static_configs:
          - targets: ["order-gateway:8080"]

      - job_name: "stock-service"
        static_configs:
          - targets: ["stock-service:4002"]

      - job_name: "kitchen-service"
        static_configs:
          - targets: ["kitchen-service:4003"]

      - job_name: "notification-hub"
        static_configs:
          - targets: ["notification-hub:4005"]
