apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-ui
  namespace: cafeteria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-ui
  template:
    metadata:
      labels:
        app: student-ui
    spec:
      containers:
        - name: student-ui
          image: docker.io/library/student-ui:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: student-ui
  namespace: cafeteria
spec:
  type: LoadBalancer
  selector:
    app: student-ui
  ports:
    - port: 3000
      targetPort: 80
      nodePort: 30000
